// Catalogo de iconos estaticos arrastrables al mapa.
// Los PNG viven en data/assets/static_icons/ y viajan dentro de
// frontend-data en el paquete de proyecto descargable/respaldable.

export const STATIC_ICON_KEYS = [
  "amusement_park",
  "auditorium",
  "bakery",
  "break_room",
  "break_room2",
  "building",
  "bus_station",
  "cafeteria",
  "car_parking",
  "casino",
  "changing_room",
  "cinema",
  "class",
  "classroom",
  "classroom2",
  "computer_room",
  "decoration",
  "disabled_toilet",
  "drinking_fountain",
  "elevator",
  "entranceexit",
  "fast_food",
  "fruits_and_vegetables",
  "gym",
  "hall",
  "hotel",
  "information_desk",
  "library",
  "liquor",
  "meeting_area",
  "meeting_available",
  "meeting_point",
  "meeting_room",
  "meeting_room2",
  "mens_restroom",
  "menwomen_restroom",
  "movie_rental",
  "night_club",
  "office",
  "office-dark",
  "park",
  "pharmacy",
  "printer",
  "quiet_zone",
  "ramp",
  "reception",
  "reception_2",
  "recycle",
  "restaurant",
  "restroom_2",
  "room",
  "school",
  "seating_area",
  "stairs",
  "stairs_2",
  "storage",
  "studio_photo",
  "technical_room",
  "technical_room_2",
  "technical_room_3",
  "technical_room_4",
  "toilet_mendisabled",
  "tv",
  "university",
  "welcome_house",
  "wifi",
  "womens_restroom",
  "womens_restroom_2",
];

export const STATIC_ICON_LABELS = {
  amusement_park: "Parque de juegos",
  auditorium: "Auditorio",
  bakery: "Panaderia",
  break_room: "Sala de descanso",
  break_room2: "Sala de descanso 2",
  building: "Edificio",
  bus_station: "Paradero de buses",
  cafeteria: "Cafeteria",
  car_parking: "Estacionamiento",
  casino: "Juegos",
  changing_room: "Vestuario",
  cinema: "Cine",
  class: "Clase",
  classroom: "Sala de clases",
  classroom2: "Sala de clases 2",
  computer_room: "Sala de computacion",
  decoration: "Decoracion",
  disabled_toilet: "Bano accesible",
  drinking_fountain: "Bebedero",
  elevator: "Ascensor",
  entranceexit: "Puerta (entrada/salida)",
  fast_food: "Comida rapida",
  fruits_and_vegetables: "Verduras y frutas",
  gym: "Gimnasio",
  hall: "Hall",
  hotel: "Hotel",
  information_desk: "Informaciones",
  library: "Biblioteca",
  liquor: "Licores",
  meeting_area: "Zona de reunion",
  meeting_available: "Sala disponible",
  meeting_point: "Punto de encuentro",
  meeting_room: "Sala de reuniones",
  meeting_room2: "Sala de reuniones 2",
  mens_restroom: "Bano hombres",
  menwomen_restroom: "Bano compartido",
  movie_rental: "Video club",
  night_club: "Discoteca",
  office: "Oficina",
  "office-dark": "Oficina (oscuro)",
  park: "Parque",
  pharmacy: "Farmacia",
  printer: "Impresora",
  quiet_zone: "Zona silenciosa",
  ramp: "Rampa",
  reception: "Recepcion",
  reception_2: "Recepcion 2",
  recycle: "Reciclaje",
  restaurant: "Restaurante",
  restroom_2: "Bano 2",
  room: "Sala",
  school: "Escuela",
  seating_area: "Zona de asientos",
  stairs: "Escalera",
  stairs_2: "Escalera 2",
  storage: "Bodega",
  studio_photo: "Estudio fotografico",
  technical_room: "Sala tecnica",
  technical_room_2: "Sala tecnica 2",
  technical_room_3: "Sala tecnica 3",
  technical_room_4: "Sala tecnica 4",
  toilet_mendisabled: "Bano adaptado",
  tv: "Television",
  university: "Universidad",
  welcome_house: "Casa de bienvenida",
  wifi: "Wi-Fi",
  womens_restroom: "Bano mujeres",
  womens_restroom_2: "Bano mujeres 2",
};

export const staticIconUrl = (key) => `data/assets/static_icons/${key}.png`;

export const staticIconLabel = (key) => STATIC_ICON_LABELS[key] || key;